name: Astronomer CI - Deploy code

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}
  DEPLOYMENT_ID: ${{ vars.DEPLOYMENT_ID_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.4
